### ISSUE TITLE
Steam Folder is not detected on Steam Deck

### ISSUE THREAD

**Issue by RaptorTrap** [Tormak9970/Steam-Art-Manager#173]
On the Steam Deck, after upgrading to 3.6, the Steam folder is not detected and after selecting it or entering '/home/deck/.steam/steam' into the box on the dialog, the error ' The chosen path is not valid!' is displayed

![error](https://github.com/Tormak9970/Steam-Art-Manager/assets/49608875/0580e287-afec-4df0-bedd-c4921d9a5d1b)

logs:
> [Steam Art Manager] [22:28:25] [INFO]: Initialized logging file
> [Steam Art Manager] [22:28:26] [INFO]: Initializing CacheController...
> [Steam Art Manager] [22:28:26] [INFO]: Found cache dir.
> [Steam Art Manager] [22:28:26] [INFO]: Found grids cache dir.
> [Steam Art Manager] [22:28:26] [INFO]: Found Capsule cache dir.
> [Steam Art Manager] [22:28:26] [INFO]: Finished checking settings for new app version and/or migration.
> [Steam Art Manager] [22:28:26] [INFO]: Added /home/deck/.steam/steam to scope.
> [Steam Art Manager] [22:28:26] [INFO]: Found Wide Capsule cache dir.
> [Steam Art Manager] [22:28:26] [INFO]: Added /home/deck/.steam/steam to scope.
> [Steam Art Manager] [22:28:26] [INFO]: Found Hero cache dir.
> [Steam Art Manager] [22:28:26] [INFO]: Found Logo cache dir.
> [Steam Art Manager] [22:28:26] [WARNING]: Steam Not Found
> [Steam Art Manager] [22:28:26] [INFO]: Found Icon cache dir.
> [Steam Art Manager] [22:28:26] [INFO]: Initialized CacheController.
> [Steam Art Manager] [22:28:34] [INFO]: Added /home/deck/.steam/steam to scope.

Steam Deck Stable Branch OS Version 3.5.19

**Comment by Tormak9970** [comment]
Damn, probably a symlink issue. I'll take a look

**Comment by Notakas** [comment]
I'm getting the same issue on desktop. 
Running Archlinux, trying to point Steam root directory to ~/.local/share/Steam but it says it's not valid.

**Comment by Tormak9970** [comment]
@Notakas @RaptorTrap It is indeed a symlink issue. Going to fix it, but for now change the path to `/home/decl/.local/share/Steam` and itll work

**Comment by Tormak9970** [comment]
fixed as of https://github.com/Tormak9970/Steam-Art-Manager/commit/4051e316eca31ba24a888181a6a2bd0bc4075e6b. It will be included with the next release

**Comment by RaptorTrap** [comment]
Sorry, but with 3.6.1 I am still getting the same error that the steam path is not detected and the entered steam paths are not correct.

**Comment by Tormak9970** [comment]
> Sorry, but with 3.6.1 I am still getting the same error that the steam path is not detected and the entered steam paths are not correct.

Odd, I'll look into it again

**Comment by Tormak9970** [comment]
it was an issue with how tauri handles paths on the frontend. switched it to be handled in rust and its working properly now https://github.com/Tormak9970/Steam-Art-Manager/commit/b827f13b6738497be95fbe2dc83b96ec39a5d7b0. building a new release rn that'll contain the fix

**Comment by RaptorTrap** [comment]
Working perfectly now with 3.6.2, thank you!
