### ISSUE TITLE
Updated to 3.6.2 and I get PANIC on start.

### ISSUE THREAD

**Issue by kdliu86** [Tormak9970/Steam-Art-Manager#182]
It says to open the log file but I don't have one (that I can find).

Version 2.90 installed using the linux-installer.sh opens fine.

**Comment by Tormak9970** [comment]
> It says to open the log file but I don't have one (that I can find).
> 
> Version 2.90 installed using the linux-installer.sh opens fine.

What's your steam install path? I encountered this initially during some testing but i thought I covered all edge cases. The log file should be in `~/.config/dev.tormak.steam-art-manager/logs`

**Comment by kdliu86** [comment]
Hey it's the default steam deck install:
```

[Steam Art Manager] [13:57:19] [INFO]: Initialized logging file
[Steam Art Manager] [13:57:20] [INFO]: Initializing CacheController...
[Steam Art Manager] [13:57:20] [INFO]: Created cache dir.
[Steam Art Manager] [13:57:20] [INFO]: Created grids cache dir.
[Steam Art Manager] [13:57:20] [INFO]: Finished checking settings for new app version and/or migration.
[Steam Art Manager] [13:57:20] [INFO]: Created Capsule cache dir.
[Steam Art Manager] [13:57:20] [INFO]: Added /home/deck/.local/share/Steam to scope.
[Steam Art Manager] [13:57:20] [INFO]: Created Wide Capsule cache dir.
[Steam Art Manager] [13:57:20] [INFO]: Checking config/loginusers.vdf for current user info.
[Steam Art Manager] [13:57:20] [INFO]: Loaded 1 steam users.
[Steam Art Manager] [13:57:20] [WARNING]: The SteamGridDB API key found in settings is no longer valid.
[Steam Art Manager] [13:57:20] [INFO]: Loaded 0 custom game names.
[Steam Art Manager] [13:57:20] [INFO]: Finished loading app settings.
[Steam Art Manager] [13:57:20] [INFO]: Added /home/deck/.local/share/Steam to scope.
[Steam Art Manager] [13:57:20] [INFO]: App setup complete.
[Steam Art Manager] [13:57:20] [INFO]: App loaded. IsOnline: true.
[Steam Art Manager] [13:57:20] [INFO]: Loading non-steam games...
[Steam Art Manager] [13:57:20] [INFO]: Getting steam shortcuts.vdf...
[Steam Art Manager] [13:57:20] [INFO]: shortcuts.vdf exists, reading...
[Steam Art Manager] [13:57:20] [INFO]: Updated setting steamInstallPath to "/home/deck/.local/share/Steam".
[Steam Art Manager] [13:57:20] [INFO]: Added /home/deck/.local/share/Steam to scope.
[Steam Art Manager] [13:57:21] [INFO]: Updated setting debugMode to false.
[Steam Art Manager] [13:57:21] [INFO]: Loaded non-steam games.
[Steam Art Manager] [13:57:21] [INFO]: Getting steam games...
[Steam Art Manager] [13:57:21] [INFO]: Getting steam grids folder...
[Steam Art Manager] [13:57:21] [INFO]: Created Hero cache dir.
[Steam Art Manager] [13:57:21] [INFO]: Grids loaded.
[Steam Art Manager] [13:57:21] [INFO]: Getting steam library cache folder...
[Steam Art Manager] [13:57:21] [INFO]: Created Logo cache dir.
[Steam Art Manager] [13:57:21] [INFO]: Created Icon cache dir.
[Steam Art Manager] [13:57:21] [INFO]: Initialized CacheController.
[Steam Art Manager] [13:57:21] [INFO]: Library Cache loaded.
[Steam Art Manager] [13:57:21] [INFO]: Cached logo positions for 1 games.
[Steam Art Manager] [13:57:21] [INFO]: Loading games from Steam Community page...
[Steam Art Manager] [13:57:23] [INFO]: Skipping update v3.6.2.
[Steam Art Manager] [13:57:23] [INFO]: Added /home/deck/.local/share/Steam to scope.
[Steam Art Manager] [13:57:35] [INFO]: Loaded 1939 games from Steam Community page.
[Steam Art Manager] [13:57:35] [INFO]: Steam games loaded.

```

**Comment by Tormak9970** [comment]
> Hey it's the default steam deck install:
> 
> ```
> 
> [Steam Art Manager] [13:57:19] [INFO]: Initialized logging file
> [Steam Art Manager] [13:57:20] [INFO]: Initializing CacheController...
> [Steam Art Manager] [13:57:20] [INFO]: Created cache dir.
> [Steam Art Manager] [13:57:20] [INFO]: Created grids cache dir.
> [Steam Art Manager] [13:57:20] [INFO]: Finished checking settings for new app version and/or migration.
> [Steam Art Manager] [13:57:20] [INFO]: Created Capsule cache dir.
> [Steam Art Manager] [13:57:20] [INFO]: Added /home/deck/.local/share/Steam to scope.
> [Steam Art Manager] [13:57:20] [INFO]: Created Wide Capsule cache dir.
> [Steam Art Manager] [13:57:20] [INFO]: Checking config/loginusers.vdf for current user info.
> [Steam Art Manager] [13:57:20] [INFO]: Loaded 1 steam users.
> [Steam Art Manager] [13:57:20] [WARNING]: The SteamGridDB API key found in settings is no longer valid.
> [Steam Art Manager] [13:57:20] [INFO]: Loaded 0 custom game names.
> [Steam Art Manager] [13:57:20] [INFO]: Finished loading app settings.
> [Steam Art Manager] [13:57:20] [INFO]: Added /home/deck/.local/share/Steam to scope.
> [Steam Art Manager] [13:57:20] [INFO]: App setup complete.
> [Steam Art Manager] [13:57:20] [INFO]: App loaded. IsOnline: true.
> [Steam Art Manager] [13:57:20] [INFO]: Loading non-steam games...
> [Steam Art Manager] [13:57:20] [INFO]: Getting steam shortcuts.vdf...
> [Steam Art Manager] [13:57:20] [INFO]: shortcuts.vdf exists, reading...
> [Steam Art Manager] [13:57:20] [INFO]: Updated setting steamInstallPath to "/home/deck/.local/share/Steam".
> [Steam Art Manager] [13:57:20] [INFO]: Added /home/deck/.local/share/Steam to scope.
> [Steam Art Manager] [13:57:21] [INFO]: Updated setting debugMode to false.
> [Steam Art Manager] [13:57:21] [INFO]: Loaded non-steam games.
> [Steam Art Manager] [13:57:21] [INFO]: Getting steam games...
> [Steam Art Manager] [13:57:21] [INFO]: Getting steam grids folder...
> [Steam Art Manager] [13:57:21] [INFO]: Created Hero cache dir.
> [Steam Art Manager] [13:57:21] [INFO]: Grids loaded.
> [Steam Art Manager] [13:57:21] [INFO]: Getting steam library cache folder...
> [Steam Art Manager] [13:57:21] [INFO]: Created Logo cache dir.
> [Steam Art Manager] [13:57:21] [INFO]: Created Icon cache dir.
> [Steam Art Manager] [13:57:21] [INFO]: Initialized CacheController.
> [Steam Art Manager] [13:57:21] [INFO]: Library Cache loaded.
> [Steam Art Manager] [13:57:21] [INFO]: Cached logo positions for 1 games.
> [Steam Art Manager] [13:57:21] [INFO]: Loading games from Steam Community page...
> [Steam Art Manager] [13:57:23] [INFO]: Skipping update v3.6.2.
> [Steam Art Manager] [13:57:23] [INFO]: Added /home/deck/.local/share/Steam to scope.
> [Steam Art Manager] [13:57:35] [INFO]: Loaded 1939 games from Steam Community page.
> [Steam Art Manager] [13:57:35] [INFO]: Steam games loaded.
> ```

Is it still throwing the panic?

**Comment by kdliu86** [comment]
```
[Steam Art Manager] [14:31:34] [INFO]: Initialized logging file
[Steam Art Manager] [14:31:35] [INFO]: Initializing CacheController...
[Steam Art Manager] [14:31:35] [INFO]: Found cache dir.
[Steam Art Manager] [14:31:35] [INFO]: Found grids cache dir.
[Steam Art Manager] [14:31:35] [INFO]: Found Capsule cache dir.
[Steam Art Manager] [14:31:35] [INFO]: Finished checking settings for new app version and/or migration.
[Steam Art Manager] [14:31:35] [INFO]: Added /home/deck/.local/share/Steam to scope.
[Steam Art Manager] [14:31:35] [INFO]: Found Wide Capsule cache dir.
[Steam Art Manager] [14:31:35] [INFO]: Checking config/loginusers.vdf for current user info.
[Steam Art Manager] [14:31:35] [INFO]: Loaded 1 steam users.
[Steam Art Manager] [14:31:35] [WARNING]: The SteamGridDB API key found in settings is no longer valid.
[Steam Art Manager] [14:31:35] [INFO]: Loaded 0 custom game names.
[Steam Art Manager] [14:31:35] [INFO]: Finished loading app settings.
[Steam Art Manager] [14:31:35] [INFO]: Added /home/deck/.local/share/Steam to scope.
[Steam Art Manager] [14:31:35] [INFO]: App setup complete.
[Steam Art Manager] [14:31:35] [INFO]: App loaded. IsOnline: true.
[Steam Art Manager] [14:31:35] [INFO]: Loading non-steam games...
[Steam Art Manager] [14:31:35] [INFO]: Getting steam shortcuts.vdf...
[Steam Art Manager] [14:31:35] [INFO]: shortcuts.vdf exists, reading...
[Steam Art Manager] [14:31:35] [ERROR]: PANIC: File 'src/main.rs' at line 541: Should have been able to resolve target path.: Os { code: 2, kind: NotFound, message: "No such file or directory" }
[Steam Art Manager] [14:31:35] [ERROR]: Please open an issue at https://github.com/Tormak9970/Steam-Art-Manager/issues
[Steam Art Manager] [14:31:35] [INFO]: Found Hero cache dir.
[Steam Art Manager] [14:31:35] [INFO]: Updated setting steamInstallPath to "/home/deck/.local/share/Steam".
[Steam Art Manager] [14:31:35] [INFO]: Added /home/deck/.local/share/Steam to scope.
[Steam Art Manager] [14:31:35] [INFO]: Updated setting debugMode to false.
[Steam Art Manager] [14:31:35] [INFO]: Loaded non-steam games.
[Steam Art Manager] [14:31:35] [INFO]: Getting steam games...
[Steam Art Manager] [14:31:35] [INFO]: Getting steam grids folder...
[Steam Art Manager] [14:31:45] [INFO]: Grids loaded.
[Steam Art Manager] [14:31:45] [INFO]: Getting steam library cache folder...
[Steam Art Manager] [14:31:45] [INFO]: Found Logo cache dir.
[Steam Art Manager] [14:31:45] [INFO]: Found Icon cache dir.
[Steam Art Manager] [14:31:45] [INFO]: Initialized CacheController.

```

**Comment by Tormak9970** [comment]
> ```
> [Steam Art Manager] [14:31:34] [INFO]: Initialized logging file
> [Steam Art Manager] [14:31:35] [INFO]: Initializing CacheController...
> [Steam Art Manager] [14:31:35] [INFO]: Found cache dir.
> [Steam Art Manager] [14:31:35] [INFO]: Found grids cache dir.
> [Steam Art Manager] [14:31:35] [INFO]: Found Capsule cache dir.
> [Steam Art Manager] [14:31:35] [INFO]: Finished checking settings for new app version and/or migration.
> [Steam Art Manager] [14:31:35] [INFO]: Added /home/deck/.local/share/Steam to scope.
> [Steam Art Manager] [14:31:35] [INFO]: Found Wide Capsule cache dir.
> [Steam Art Manager] [14:31:35] [INFO]: Checking config/loginusers.vdf for current user info.
> [Steam Art Manager] [14:31:35] [INFO]: Loaded 1 steam users.
> [Steam Art Manager] [14:31:35] [WARNING]: The SteamGridDB API key found in settings is no longer valid.
> [Steam Art Manager] [14:31:35] [INFO]: Loaded 0 custom game names.
> [Steam Art Manager] [14:31:35] [INFO]: Finished loading app settings.
> [Steam Art Manager] [14:31:35] [INFO]: Added /home/deck/.local/share/Steam to scope.
> [Steam Art Manager] [14:31:35] [INFO]: App setup complete.
> [Steam Art Manager] [14:31:35] [INFO]: App loaded. IsOnline: true.
> [Steam Art Manager] [14:31:35] [INFO]: Loading non-steam games...
> [Steam Art Manager] [14:31:35] [INFO]: Getting steam shortcuts.vdf...
> [Steam Art Manager] [14:31:35] [INFO]: shortcuts.vdf exists, reading...
> [Steam Art Manager] [14:31:35] [ERROR]: PANIC: File 'src/main.rs' at line 541: Should have been able to resolve target path.: Os { code: 2, kind: NotFound, message: "No such file or directory" }
> [Steam Art Manager] [14:31:35] [ERROR]: Please open an issue at https://github.com/Tormak9970/Steam-Art-Manager/issues
> [Steam Art Manager] [14:31:35] [INFO]: Found Hero cache dir.
> [Steam Art Manager] [14:31:35] [INFO]: Updated setting steamInstallPath to "/home/deck/.local/share/Steam".
> [Steam Art Manager] [14:31:35] [INFO]: Added /home/deck/.local/share/Steam to scope.
> [Steam Art Manager] [14:31:35] [INFO]: Updated setting debugMode to false.
> [Steam Art Manager] [14:31:35] [INFO]: Loaded non-steam games.
> [Steam Art Manager] [14:31:35] [INFO]: Getting steam games...
> [Steam Art Manager] [14:31:35] [INFO]: Getting steam grids folder...
> [Steam Art Manager] [14:31:45] [INFO]: Grids loaded.
> [Steam Art Manager] [14:31:45] [INFO]: Getting steam library cache folder...
> [Steam Art Manager] [14:31:45] [INFO]: Found Logo cache dir.
> [Steam Art Manager] [14:31:45] [INFO]: Found Icon cache dir.
> [Steam Art Manager] [14:31:45] [INFO]: Initialized CacheController.
> ```

perfect, thanks. I'll look into it

**Comment by Tormak9970** [comment]
This has been fixed in https://github.com/Tormak9970/Steam-Art-Manager/commit/91d5723e893751d8105741c4e572389663567686. It'll be included in the next update

**Comment by kdliu86** [comment]
Still broken with 3.6.6.  I was able to open the app 1 time, scroll my library, then it crashed.  On 2nd load it said Steam not found.
```

[Steam Art Manager] [16:11:2] [INFO]: Initialized logging file
[Steam Art Manager] [16:11:4] [INFO]: Finished checking settings for new app version and/or migration.
[Steam Art Manager] [16:11:4] [INFO]: Added /home/deck/.local/share/Steam to scope.
[Steam Art Manager] [16:11:4] [INFO]: Checking config/loginusers.vdf for current user info.
[Steam Art Manager] [16:11:4] [INFO]: Loaded 1 steam users.
[Steam Art Manager] [16:11:4] [WARNING]: The SteamGridDB API key found in settings is no longer valid.
[Steam Art Manager] [16:11:4] [INFO]: Loaded 0 custom game names.
[Steam Art Manager] [16:11:4] [INFO]: Finished loading app settings.
[Steam Art Manager] [16:11:4] [INFO]: Added /home/deck/.local/share/Steam to scope.
[Steam Art Manager] [16:11:4] [INFO]: App setup complete.
[Steam Art Manager] [16:11:4] [INFO]: App loaded. IsOnline: true.
[Steam Art Manager] [16:11:4] [INFO]: Getting steam shortcuts.vdf...
[Steam Art Manager] [16:11:4] [INFO]: shortcuts.vdf exists, reading...
[Steam Art Manager] [16:11:4] [ERROR]: Error adding /home/deck/.local/share/steam to scope. Path does not exist.
[Steam Art Manager] [16:11:4] [INFO]: Updated setting steamInstallPath to "/home/deck/.local/share/Steam".
[Steam Art Manager] [16:11:4] [INFO]: Added /home/deck/.local/share/Steam to scope.
[Steam Art Manager] [16:11:4] [INFO]: Updated setting debugMode to false.
[Steam Art Manager] [16:11:4] [INFO]: Loaded non-steam games.
[Steam Art Manager] [16:11:4] [INFO]: Getting steam grids folder...
[Steam Art Manager] [16:11:4] [INFO]: Grids loaded.
[Steam Art Manager] [16:11:4] [INFO]: Getting steam library cache folder...
[Steam Art Manager] [16:11:4] [INFO]: Initialized CacheController.
[Steam Art Manager] [16:11:4] [INFO]: Library Cache loaded.
[Steam Art Manager] [16:11:4] [INFO]: Cached logo positions for 1 games.

```
