### ISSUE TITLE
SARM not loading grids.

### ISSUE THREAD

**Issue by brianx87** [Tormak9970/Steam-Art-Manager#185]
SARM not loading new grids into right pane. Upon selecting a game in the centre pane SARM states 'no results found' on every game and the browsing drop down menu on the right pane will only output the first game that is selected. Sometimes upon restarting SARM the first game selected will load a grid image set on the right, the only way to get SARM to load another set is to switch between Steam and Non-Steam games.

Restart SARM, reinstall SARM

Upon opening and selecting a game to change the grid, the right pane should load a set of new grid images to select from and change the browsing drop down menu to reflect the title of selected game.

Reverting to v3.6.2 has resolved the issue.

Windows 10 22H2 19045.4291

LOG:
```
[Steam Art Manager] [7:54:49] [INFO]: Found Capsule cache dir.
[Steam Art Manager] [7:54:49] [INFO]: Added d:/steam/steam to scope.
[Steam Art Manager] [7:54:49] [INFO]: Added \\?\D:\Steam\Steam to scope.
[Steam Art Manager] [7:54:49] [INFO]: Found Wide Capsule cache dir.
[Steam Art Manager] [7:54:49] [INFO]: Checking config/loginusers.vdf for current user info.
[Steam Art Manager] [7:54:49] [INFO]: Loaded 1 steam users.
[Steam Art Manager] [7:54:49] [INFO]: Found Hero cache dir.
[Steam Art Manager] [7:54:49] [INFO]: Found Logo cache dir.
[Steam Art Manager] [7:54:49] [INFO]: Found Icon cache dir.
[Steam Art Manager] [7:54:49] [INFO]: Initialized CacheController.
[Steam Art Manager] [7:54:50] [INFO]: Loaded 2 custom game names.
[Steam Art Manager] [7:54:50] [INFO]: Finished loading app settings.
[Steam Art Manager] [7:54:50] [INFO]: Added d:/steam/steam to scope.
[Steam Art Manager] [7:54:50] [INFO]: App setup complete.
[Steam Art Manager] [7:54:50] [INFO]: App loaded. IsOnline: true.
[Steam Art Manager] [7:54:50] [INFO]: Loading non-steam games...
[Steam Art Manager] [7:54:50] [INFO]: Getting steam shortcuts.vdf...
[Steam Art Manager] [7:54:50] [INFO]: shortcuts.vdf exists, reading...
[Steam Art Manager] [7:54:50] [INFO]: Updated setting steamInstallPath to "d:/steam/steam".
[Steam Art Manager] [7:54:50] [INFO]: Updated setting debugMode to false.
[Steam Art Manager] [7:54:50] [INFO]: Added d:/steam/steam to scope.
[Steam Art Manager] [7:54:50] [INFO]: Updated setting windowSettings.main.panels to {"options":16,"games":52.83639609538784,"grids":31.16360390461216}.
[Steam Art Manager] [7:54:50] [INFO]: Loaded non-steam games.
[Steam Art Manager] [7:54:50] [INFO]: Getting steam games...
[Steam Art Manager] [7:54:50] [INFO]: Getting steam grids folder...
[Steam Art Manager] [7:54:55] [INFO]: Grids loaded.
[Steam Art Manager] [7:54:55] [INFO]: Getting steam library cache folder...
[Steam Art Manager] [7:54:56] [INFO]: Library Cache loaded.
[Steam Art Manager] [7:54:57] [INFO]: Cached logo positions for 3 games.
[Steam Art Manager] [7:54:57] [INFO]: Loading games from Steam API...
[Steam Art Manager] [7:54:58] [INFO]: Loaded 2457 games from Steam API.
[Steam Art Manager] [7:54:59] [INFO]: Steam games loaded.
[Steam Art Manager] [7:55:2] [INFO]: Finding SGDB game for 251570...
[Steam Art Manager] [7:55:2] [INFO]: Fetching grids for game 251570...
[Steam Art Manager] [7:55:2] [INFO]: Need to fetch Capsule for 3053.
[Steam Art Manager] [7:55:2] [INFO]: Query: "Capsules for 7 Days to Die". Result: 3 grids.
[Steam Art Manager] [7:55:3] [INFO]: Fetching grids for game 251570...
[Steam Art Manager] [7:55:4] [INFO]: Need to fetch page 2 of Capsule for 3053.
[Steam Art Manager] [7:55:4] [INFO]: Query: "Capsules for 7 Days to Die". Result: 3 grids.
[Steam Art Manager] [7:55:4] [INFO]: Fetching grids for game 1086010...
[Steam Art Manager] [7:55:4] [INFO]: Need to fetch page 2 of Capsule for 3053.
[Steam Art Manager] [7:55:4] [INFO]: Query: "Capsules for 198X". Result: 3 grids.
[Steam Art Manager] [7:55:5] [INFO]: Fetching grids for game 1086010...
[Steam Art Manager] [7:55:5] [INFO]: Need to fetch page 3 of Capsule for 3053.
[Steam Art Manager] [7:55:5] [INFO]: Query: "Capsules for 198X". Result: 3 grids.
[Steam Art Manager] [7:55:7] [INFO]: Fetching grids for game 427250...
[Steam Art Manager] [7:55:7] [INFO]: Need to fetch page 3 of Capsule for 3053.
[Steam Art Manager] [7:55:7] [INFO]: Query: "Capsules for 8-Bit Armies". Result: 3 grids.
[Steam Art Manager] [7:55:7] [INFO]: Fetching grids for game 427250...
[Steam Art Manager] [7:55:7] [INFO]: Need to fetch page 4 of Capsule for 3053.
[Steam Art Manager] [7:55:7] [INFO]: Query: "Capsules for 8-Bit Armies". Result: 3 grids.
[Steam Art Manager] [7:55:9] [INFO]: Finding SGDB game for 3954034053...
[Steam Art Manager] [7:55:9] [INFO]: Fetching grids for game 3954034053...
[Steam Art Manager] [7:55:9] [INFO]: Need to fetch Capsule for 36515.
[Steam Art Manager] [7:55:9] [INFO]: Query: "Capsules for PPSSPP (Emulator)". Result: 1 grids.
[Steam Art Manager] [7:55:10] [INFO]: Fetching grids for game 3954034053...
[Steam Art Manager] [7:55:10] [INFO]: Need to fetch page 2 of Capsule for 36515.
[Steam Art Manager] [7:55:10] [INFO]: Query: "Capsules for PPSSPP (Emulator)". Result: 1 grids.
[Steam Art Manager] [7:55:11] [INFO]: Fetching grids for game 2169847496...
[Steam Art Manager] [7:55:11] [INFO]: Need to fetch page 2 of Capsule for 36515.
[Steam Art Manager] [7:55:11] [INFO]: Query: "Capsules for The Simpsons: Hit & Run". Result: 1 grids.
[Steam Art Manager] [7:55:11] [INFO]: Fetching grids for game 2169847496...
[Steam Art Manager] [7:55:11] [INFO]: Need to fetch page 3 of Capsule for 36515.
[Steam Art Manager] [7:55:12] [INFO]: Query: "Capsules for The Simpsons: Hit & Run". Result: 1 grids.
[Steam Art Manager] [7:55:13] [INFO]: Fetching grids for game 2300276749...
[Steam Art Manager] [7:55:13] [INFO]: Need to fetch page 3 of Capsule for 36515.
[Steam Art Manager] [7:55:13] [INFO]: Query: "Capsules for Xenia". Result: 1 grids.
[Steam Art Manager] [7:55:13] [INFO]: Fetching grids for game 2300276749...
[Steam Art Manager] [7:55:13] [INFO]: Need to fetch page 4 of Capsule for 36515.
[Steam Art Manager] [7:55:14] [INFO]: Query: "Capsules for Xenia". Result: 1 grids.
[Steam Art Manager] [7:55:15] [INFO]: Fetching grids for game 2159253148...
[Steam Art Manager] [7:55:15] [INFO]: Need to fetch page 4 of Capsule for 36515.
[Steam Art Manager] [7:55:15] [INFO]: Query: "Capsules for Sonic & Knuckles + Sonic the Hedgehog 3". Result: 1 grids.
[Steam Art Manager] [7:55:16] [INFO]: Fetching grids for game 2159253148...
[Steam Art Manager] [7:55:16] [INFO]: Need to fetch page 5 of Capsule for 36515.
[Steam Art Manager] [7:55:16] [INFO]: Query: "Capsules for Sonic & Knuckles + Sonic the Hedgehog 3". Result: 1 grids.
[Steam Art Manager] [7:56:33] [INFO]: Finding SGDB game for 1086010...
[Steam Art Manager] [7:56:33] [INFO]: Fetching grids for game 1086010...
[Steam Art Manager] [7:56:33] [INFO]: Need to fetch Capsule for 5097913.
[Steam Art Manager] [7:56:33] [INFO]: Query: "Capsules for 198X". Result: no grids.
[Steam Art Manager] [7:56:35] [INFO]: Fetching grids for game 251570...
[Steam Art Manager] [7:56:35] [INFO]: Need to fetch page 1 of Capsule for 5097913.
[Steam Art Manager] [7:56:35] [INFO]: Query: "Capsules for 7 Days to Die". Result: no grids.
[Steam Art Manager] [7:56:38] [INFO]: Finding SGDB game for 4005280097...
[Steam Art Manager] [7:56:38] [INFO]: Fetching grids for game 4005280097...
[Steam Art Manager] [7:56:38] [INFO]: Need to fetch Capsule for 3106.
[Steam Art Manager] [7:56:39] [INFO]: Query: "Capsules for Moise". Result: no grids.
[Steam Art Manager] [7:56:39] [INFO]: Fetching grids for game 2169847496...
[Steam Art Manager] [7:56:39] [INFO]: Need to fetch page 1 of Capsule for 3106.
[Steam Art Manager] [7:56:39] [INFO]: Query: "Capsules for The Simpsons: Hit & Run". Result: no grids.
[Steam Art Manager] [7:56:55] [INFO]: Added \\?\D:\Steam\Steam to scope.
```

**Comment by Tormak9970** [comment]
fixed with https://github.com/Tormak9970/Steam-Art-Manager/commit/31672e5b685b5e2b8dadac3a4e14e6ab4837a0ce. Wasn't properly resetting the steamGrid stuff when games changed

**Comment by brianx87** [comment]
Latest updated didn't fix the issue for me. Results are slightly different, it loads some non-steam images but no Steam images into the right pane.

**Comment by Tormak9970** [comment]
what's weird is that the only difference between this and my setup is that steam is on another drive, but that shouldn't have any effect on the SteamGridDB parts of the app. Gonna try and do more testing

**Comment by Tormak9970** [comment]
@brianx87 what filters do you have enabled?

**Comment by brianx87** [comment]
![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/11686648/bc8ce3dc-1538-48a8-b05b-ed5d6c6e1158)

**Comment by Tormak9970** [comment]
This seems to be the same as #190, going to look into it today
