### ISSUE TITLE
SAM freezes when loading Artworks

### ISSUE THREAD

**Issue by RaptorTrap** [Tormak9970/Steam-Art-Manager#200]
Often SAM freezes when selecting or switching games and the Artworks are loading. The Artworks are staying grey and it completly freezes needing a force close. It happens almost everytime when Capsules are selected.

![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/49608875/fcf8e58a-c155-4aef-9cc9-f8bcc3e79d15)

Using on a Steam Deck with current Stable Branch.

**Logs:**
```
[Steam` Art Manager] [22:57:6] [INFO]: Initialized logging file
[Steam Art Manager] [22:57:7] [INFO]: Finished checking settings for new app version and/or migration.
[Steam Art Manager] [22:57:7] [INFO]: Added /home/deck/.steam/steam to scope.
[Steam Art Manager] [22:57:7] [INFO]: Checking config/loginusers.vdf for current user info.
[Steam Art Manager] [22:57:7] [INFO]: Loaded 1 steam users.
[Steam Art Manager] [22:57:7] [INFO]: Initialized CacheController.
[Steam Art Manager] [22:57:7] [INFO]: Loaded 4 custom game names.
[Steam Art Manager] [22:57:7] [INFO]: Finished loading app settings.
[Steam Art Manager] [22:57:7] [INFO]: App setup complete.
[Steam Art Manager] [22:57:7] [INFO]: App loaded. IsOnline: true.
[Steam Art Manager] [22:57:7] [INFO]: Getting steam shortcuts.vdf...
[Steam Art Manager] [22:57:7] [INFO]: shortcuts.vdf exists, reading...
[Steam Art Manager] [22:57:7] [INFO]: Updated setting steamInstallPath to "/home/deck/.steam/steam".
[Steam Art Manager] [22:57:7] [INFO]: Updated setting debugMode to false.
[Steam Art Manager] [22:57:7] [INFO]: Loaded non-steam games.
[Steam Art Manager] [22:57:7] [INFO]: Getting steam grids folder...
[Steam Art Manager] [22:57:7] [INFO]: Grids loaded.
[Steam Art Manager] [22:57:7] [INFO]: Getting steam library cache folder...
[Steam Art Manager] [22:57:8] [INFO]: Library Cache loaded.
[Steam Art Manager] [22:57:8] [INFO]: Cached logo positions for 16 games.
[Steam Art Manager] [22:57:8] [INFO]: Loaded 626 games from Steam Community page.
[Steam Art Manager] [22:57:14] [INFO]: Finding SGDB game for 2597580300...
[Steam Art Manager] [22:57:14] [INFO]: Fetching grids for game 2597580300...
[Steam Art Manager] [22:57:15] [INFO]: Query: "Capsules for Zenless Zone Zero - page 0". Result: 27 grids.
```

**Comment by Tormak9970** [comment]
I'll look into this when I get a chance

**Comment by Wizzarkt** [comment]
hi, im not into testing or anything alike, but i did some test with multiple programs and noticed what i think is a pattern, the program works fine for any at work without too many images in a single category, for example, when trying to setup Firefox everything but capsule works, my theory is that if it isn't a bug where something overflows it could be steamgriddb that could be setting a limit in API calls and that hangs the program unexpectedly as it tries to load hundreds of images within said category

**Comment by Tormak9970** [comment]
> hi, im not into testing or anything alike, but i did some test with multiple programs and noticed what i think is a pattern, the program works fine for any art work without too many images in a single category, for example, when trying to setup Firefox everything but capsule works, my theory is that if it isn't a bug where something overflows it could be steamgriddb that could be setting a limit in API calls and that hangs the program unexpectedly as it tries to load hundreds of images within said category

I can check with the maintainer of SGDB but that shouldn't cause a freeze, SGDB will return an error if its rate limited, and SARM has timeouts on all requests. I'll do some testing and see if I can figure it out

**Comment by Tormak9970** [comment]
@Wizzarkt can you share some of the other titles you tried? Firefox seems to work fine for me, but its possible it has something to do with loading multiple games with large capsule counts one after the other

**Comment by m0tholith** [comment]
@Tormak9970 I think this freezing happens mostly when trying to display animated artwork. If I open a game with animated artwork available (such as TEKKEN 8's hero art) it freezes, however if I disable animated artwork before opening, it comes back up. So I'm pretty sure that's broken...

**Comment by Tormak9970** [comment]
> @Tormak9970 I think this freezing happens mostly when trying to display animated artwork. If I open a game with animated artwork available (such as TEKKEN 8's hero art) it freezes, however if I disable animated artwork before opening, it comes back up. So I'm pretty sure that's broken...

What platform are you on? Testing on windows animated capsules seem to work fine. I haven't tested animated heroes in a while so I will take a look at that

**Comment by m0tholith** [comment]
Sorry I should've mentioned that. I'm on NixOS 24.05 (Linux 6.9.10).

**Comment by RaptorTrap** [comment]
Can confirm, disabling animated artworks fixed the freezing for me, tested with Zenless Zone Zero.

**Comment by Tormak9970** [comment]
Ok thats super helpful. So this is likely a related to WebKit (the tool used to render the app on Linux), which makes sense as it often has issues with images/videos. I'll do some testing and try to get it fixed

**Comment by Wizzarkt** [comment]
> @Wizzarkt can you share some of the other titles you tried? Firefox seems to work fine for me, but its possible it has something to do with loading multiple games with large capsule counts one after the other

im running SteamOS (arch Linux btw) and i can confirm that disabling animated stuff fixed it, so maybe the reason why Firefox capsules freeze, is not because it has a big library (as i previously suggested) but because is so big that someone at some point uploaded an animated one.

**Comment by m0tholith** [comment]
TEKKEN 8 has lots of artwork (not just animated, even static) so even opening the same menu without animated art works just fine, in some cases there is only one animated art entry which hangs the entire program. Here's a log for what happens the moment I enable animated artwork in TEKKEN 8 (heros): [paste](https://paste.rs/rSIOB)

**Comment by Tormak9970** [comment]
It seems like at some point, bundling media frameworks on linux got disabled. Correcting that resolved the issue. Fixed as of https://github.com/Tormak9970/Steam-Art-Manager/commit/cb1045665de16201ffe91bbf8f731ad536553c13

**Comment by gothickitty93** [comment]
I think this issue is still present. Whenever I switch games that don't seem to have any entries, the entire app freezes.
![Screenshot 2024-11-02 141243](https://github.com/user-attachments/assets/6e19cc51-425d-4f79-8c55-76c4fcee50cd)

https://github.com/user-attachments/assets/3a5cbe8e-0b3b-4469-8228-c3cecb78f035

**Comment by Tormak9970** [comment]
@gothickitty93 It is still happening. I fixed the issue with https://github.com/Tormak9970/Steam-Art-Manager/commit/c7ac1c59791db776a8e7c53eb200dd6657214059, so a new build should be up soon with the fix

**Comment by gothickitty93** [comment]
Thanks!
