### ISSUE TITLE
path/api keys not being recognised/saved (windows)

### ISSUE THREAD

**Issue by jali-peno** [Tormak9970/Steam-Art-Manager#216]
**Describe the bug**
1-) program doesnt save path/api keys (possibly because of 2)
2-) program doesnt recognise steam api key

**To Reproduce**
1-) fresh install of app
2-) go to settings to configure path/keys, all will be empty by default (odd because steam is installed to the default location)
3-) input information, press save
4-) program doesnt save information, supposedly invalid path and steam api key

**Expected behavior**
settings menu saves data correctly

**Screenshots**
before pressing save and closing window:
![image](https://github.com/user-attachments/assets/02a94510-f004-4cff-8a46-4d426251d410)

after saving and reopening settings:
![image](https://github.com/user-attachments/assets/2c2f5476-5ea6-411f-b5a3-8d8ca3f8e6fc)

**Logs:**
[Steam Art Manager] [9:16:13] [INFO]: Initialized logging file
[Steam Art Manager] [9:16:13] [INFO]: Initialized CacheController.
[Steam Art Manager] [9:16:39] [INFO]: Added c:\program files (x86)\steam to scope.
[Steam Art Manager] [9:16:46] [INFO]: Saving settings...
[Steam Art Manager] [9:16:47] [INFO]: Saving settings...
[Steam Art Manager] [9:16:48] [INFO]: Saving settings...
[Steam Art Manager] [9:16:48] [INFO]: Saving settings...

**System information (please complete the following information):**
 - OS: windows 11 23h2
 - Version 3.10.1

**Additional information**
this is only happening on my laptop, works fine on my desktop with the same windows and client version

**Comment by Tormak9970** [comment]
Will look into this

**Comment by bobbybroski** [comment]
same with me it will not save

**Comment by bobbybroski** [comment]
steam user also just says loading... and will not load any games

**Comment by Tormak9970** [comment]
fixed with https://github.com/Tormak9970/Steam-Art-Manager/commit/e9fe68ea107742194161fbf2593b5fd16383be44. A new release is building now, and will include the fix

**Comment by BenjiBearPup** [comment]
Im still having issues. I uninstalled the previous version and downloaded the new release.
It says the Steam Install Path is valid and same for the SteamGrid Api Key.

For the Steam api key when I paste my Steam api key in it says it's invalid. 

And when I click save changes nothing is happening. The window stays open. The program is still running just I can't save changes and Steam Api Key isn't being recognised properly.

**Comment by jali-peno** [comment]
try deleting the old program config file like i mentioned above, assuming youre on windows you can get there easily by pressing win+r, then typing %appdata% into the box and hitting enter

**Comment by BenjiBearPup** [comment]
> try deleting the old program config file like i mentioned above, assuming youre on windows you can get there easily by pressing win+r, then typing %appdata% into the box and hitting enter

I did try that. But I couldn't find a folder for SteamArtManager unless it's named something else? I'm using Windows 10

**Comment by BenjiBearPup** [comment]
> Forgot to mention that. You do need to delete the dev.tormak.steam-art-manager file in AppData/Roaming

It's working perfectly now! All games showing and art changes are saving and showing up in Steam. Thanks so much!
