### ISSUE TITLE
Export/Import not working

### ISSUE THREAD

**Issue by brianx87** [Tormak9970/Steam-Art-Manager#243]
The Export/Import feature is broken for me, upon exporting it stops at 2.3GB with around 7K files which if I attempt to import on another PC SARM crashes. I should have over 5-7GB of files as per an old export, with 3K games and several files per game my file count is very low and the logs give no indication of errors.

Import Log
```
[Steam Art Manager] [22:47:35] [INFO]: Initialized logging file
[Steam Art Manager] [22:47:35] [INFO]: Finished checking settings for new app version and/or migration.
[Steam Art Manager] [22:47:35] [INFO]: Added d:/steam to scope.
[Steam Art Manager] [22:47:35] [INFO]: Checking config/loginusers.vdf for current user info.
[Steam Art Manager] [22:47:35] [INFO]: Loaded 1 steam users.
[Steam Art Manager] [22:47:35] [INFO]: Loaded 0 custom game names.
[Steam Art Manager] [22:47:35] [INFO]: Finished loading app settings.
[Steam Art Manager] [22:47:35] [INFO]: App setup complete.
[Steam Art Manager] [22:47:35] [INFO]: App loaded. IsOnline: true.
[Steam Art Manager] [22:47:35] [INFO]: Getting steam library cache folder...
[Steam Art Manager] [22:47:35] [INFO]: Initialized CacheController.
[Steam Art Manager] [22:47:35] [INFO]: Updated setting steamInstallPath to "d:/steam".
[Steam Art Manager] [22:47:35] [INFO]: Updated setting debugMode to false.
[Steam Art Manager] [22:47:35] [INFO]: Getting steam shortcuts.vdf...
[Steam Art Manager] [22:47:35] [INFO]: shortcuts.vdf exists, reading...
[Steam Art Manager] [22:47:36] [INFO]: Loaded 3942 games from Steam API.
[Steam Art Manager] [22:47:36] [INFO]: Loading Grids Cache...
[Steam Art Manager] [22:47:36] [INFO]: Getting steam grids folder...
[Steam Art Manager] [22:47:36] [INFO]: Getting steam library cache folder...
[Steam Art Manager] [22:47:37] [INFO]: Added d:/steam to scope.
[Steam Art Manager] [22:47:41] [INFO]: Loaded grids for 4111 apps.
[Steam Art Manager] [22:47:41] [INFO]: Cached logo positions for 0 games.
[Steam Art Manager] [22:47:52] [INFO]: Prompting user to grids.
[Steam Art Manager] [22:47:59] [INFO]: Got file path: C:\Users\\Downloads\Steam_Grids_Export.zip
[Steam Art Manager] [22:47:59] [INFO]: Getting steam grids folder...
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1000030__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1000030__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1000030__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1000030__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1004750__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1004750__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1004750__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1004750__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__10090__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__10090__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__10090__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__10090__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__10110__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__10110__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__10110__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__10110__logo.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1016120__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1016120__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1016120__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1016120__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1017900__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1017900__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1017900__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1017900__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__102600__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__102600__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__102600__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__102600__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__102810__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__102810__capsule.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__102810__hero.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__102810__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1030840__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1035320__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1035320__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1035320__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1035320__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1038250__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1038250__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1038250__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1038250__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__10460__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__10460__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__10460__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__10460__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__104900__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__104900__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__104900__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__104900__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__10500__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__105000__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__105000__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__105000__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__105000__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__10500__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__10500__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__10500__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__105100__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__105100__capsule.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__105100__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__105100__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1051200__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1051200__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1051200__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1051200__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__105600__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__105600__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__105600__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__105600__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__105700__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__105700__capsule.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__105700__hero.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__105700__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__105800__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__105800__capsule.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__105800__hero.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__105800__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1058020__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1058020__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1058020__logo.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1066890__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1066890__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1066890__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1066890__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__10680__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__10680__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__10680__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__10680__logo.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__10680__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__107100__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__107100__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__107100__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__107100__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1073910__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1073910__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1073910__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1073910__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__107410__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__107410__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1078920__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1078920__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1078920__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1078920__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1080110__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1080110__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1080110__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1080110__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__108200__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__108200__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__108200__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__108200__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__108500__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__108500__capsule.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__108500__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__108500__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1085660__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1085660__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1085660__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__108600__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__108600__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__108600__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__108600__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__108710__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__108710__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__108710__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__108710__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__108800__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__108800__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__108800__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__108800__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1091500__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1091500__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1096570__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1096570__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1096570__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1096570__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11040__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11040__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11040__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11040__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11050__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11050__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11050__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11050__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11130__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11130__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11130__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11130__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11140__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11140__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11140__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11140__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11150__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11150__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11150__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11150__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__111600__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__111600__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__111600__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__111600__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11180__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11180__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11180__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11180__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__111900__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__111900__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__111900__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__111900__logo.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__112100__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__112100__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__112100__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__112100__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11250__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11250__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11250__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11250__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1125480__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1125480__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1125480__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1125480__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__113200__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__113200__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__113200__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__113200__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11370__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11370__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11370__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11370__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11390__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11390__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11390__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11390__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11420__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11420__capsule.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11420__hero.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11420__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1142100__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1142100__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1142100__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1142100__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11450__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11450__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11450__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11450__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1150440__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1150440__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1150440__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1150440__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11590__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11590__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11590__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__11590__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__116120__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__116120__capsule.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__116120__hero.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__116120__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1172380__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1172380__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1172380__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1172380__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1174180__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1174180__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1174180__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1174180__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1178780__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1178780__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1178780__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1178780__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1187330__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1187330__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1187330__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1187330__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1196590__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1196590__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1196590__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1196590__logo.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1196590__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__12100__logo.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1213210__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1213210__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1213210__hero.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__1213210__logo.png.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__12140__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__12140__capsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__12150__widecapsule.jpg.
[Steam Art Manager] [22:47:59] [INFO]: Wrote zip entry steam__12150__capsule.jpg.
[Steam Art Manager] [22:48:0] [INFO]: Wrote zip entry steam__12170__capsule.jpg.
[Steam Art Manager] [22:48:0] [INFO]: Wrote zip entry steam__12170__hero.jpg.
[Steam Art Manager] [22:48:0] [INFO]: Wrote zip entry steam__12170__logo.jpg.
[Steam Art Manager] [22:48:0] [INFO]: Wrote zip entry steam__12180__capsule.jpg.
[Steam Art Manager] [22:48:0] [INFO]: Wrote zip entry steam__12210__capsule.jpg.
[Steam Art Manager] [22:48:0] [INFO]: Wrote zip entry steam__1222670__widecapsule.jpg.
[Steam Art Manager] [22:48:0] [INFO]: Wrote zip entry steam__1222670__capsule.jpg.
[Steam Art Manager] [22:48:0] [INFO]: Wrote zip entry steam__1222670__hero.jpg.
[Steam Art Manager] [22:48:0] [INFO]: Wrote zip entry steam__1222670__logo.png.
[Steam Art Manager] [22:48:0] [INFO]: Wrote zip entry steam__1222680__widecapsule.jpg.
[Steam Art Manager] [22:48:0] [INFO]: Wrote zip entry steam__1222680__capsule.jpg.

```

**Comment by Tormak9970** [comment]
I suspect this is related to https://github.com/Tormak9970/Steam-Art-Manager/issues/241. I'll try to get this fixed soon

**Comment by Tormak9970** [comment]
@brianx87 can you try creating an export with https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/rc-3.10.8 and (assuming that works), try importing it? The export should be fixed, not sure if the import is though

**Comment by brianx87** [comment]
Steam Deck version of this update doesn't launch for me.

Downgrading to previous version works fine.

**Comment by Tormak9970** [comment]
> Steam Deck version of this update doesn't launch for me. Tried upgrading and fresh install.
> 
> Downgrading to previous version gets it running again.

Did you download the AppImage manually and then right click it to mark it as an executable?

**Comment by brianx87** [comment]
> > Steam Deck version of this update doesn't launch for me. Tried upgrading and fresh install.
> > Downgrading to previous version gets it running again.
> 
> Did you download the AppImage manually and then right click it to mark it as an executable?

I did yes.

I'm running the export on Windows now which has stopped at 1.97GB and not going any further although it appears to have 1K+ files more than previous attempts.

**Comment by brianx87** [comment]
My apologies, I thought you meant the script. The script isn't working, the appimage runs but no images are loading.

**Comment by Tormak9970** [comment]
> My apologies, I thought you meant the script. The script isn't working, the appimage runs but no images are loading.

I'll look into this when I get the chance. Probably the same issue as #247 . As to the export issue, can you try temporarily moving half or so of your custom grids to a temp folder, then trying to export? that'll let us know if the issue is the number of files

**Comment by brianx87** [comment]
> > My apologies, I thought you meant the script. The script isn't working, the appimage runs but no images are loading.
> 
> I'll look into this when I get the chance. Probably the same issue as [#247](https://github.com/Tormak9970/Steam-Art-Manager/issues/247) . As to the export issue, can you try temporarily moving half or so of your custom grids to a temp folder, then trying to export? that'll let us know if the issue is the number of files

No luck, I can import an old backup from an early version 3 build on Windows but not on Steam Deck, also the latest version 3.11 doesn't work for me on either Windows 10 or Steam Deck, images don't load.

**Comment by Tormak9970** [comment]
> > > My apologies, I thought you meant the script. The script isn't working, the appimage runs but no images are loading.
> > 
> > I'll look into this when I get the chance. Probably the same issue as [#247](https://github.com/Tormak9970/Steam-Art-Manager/issues/247) . As to the export issue, can you try temporarily moving half or so of your custom grids to a temp folder, then trying to export? that'll let us know if the issue is the number of files
> 
> No luck, I can import an old backup from an early version 3 build on Windows but not on Steam Deck, also the latest version 3.11 doesn't work for me on either Windows 10 or Steam Deck, images don't load.

I'll look into the issue with it not working. 

Does the old export have non-steam games in it? I fixed a fail state in 3.11 when importing in case some non-steam games aren't present on that system

**Comment by Tormak9970** [comment]
Are there log files for 3.11 on your windows system?

**Comment by brianx87** [comment]
> Will reopen this if there is any information provided that can help reproduce it, as I am unable to

No problem, Linux still doesn't work, the Steam install location and Steam API aren't saving and importing is still not working.

**Comment by Tormak9970** [comment]
> > Will reopen this if there is any information provided that can help reproduce it, as I am unable to
> 
> No problem, Linux still doesn't work, the Steam install location and Steam API aren't saving and importing is still not working.

Can you share the logs from linux with the latest version?

**Comment by brianx87** [comment]
> > > Will reopen this if there is any information provided that can help reproduce it, as I am unable to
> > 
> > 
> > No problem, Linux still doesn't work, the Steam install location and Steam API aren't saving and importing is still not working.
> 
> Can you share the logs from linux with the latest version?

Where are the logs on linux?

**Comment by Tormak9970** [comment]
> > > > Will reopen this if there is any information provided that can help reproduce it, as I am unable to
> > > 
> > > 
> > > No problem, Linux still doesn't work, the Steam install location and Steam API aren't saving and importing is still not working.
> > 
> > 
> > Can you share the logs from linux with the latest version?
> 
> Where are the logs on linux?

The log file should be in `/home/YOUR_USERNAME/.config/dev.tormak.steam-art-manager/logs/core.log`

**Comment by brianx87** [comment]
> Glad to hear the app is working! Its possible there's an issue with the generic non_steam game setup I used, I'll look into it. Only thing I can think of is to make sure the non-steam apps have the same names on both machines

So Windows to SteamOS only imported the Steam games, I batch applied the non-steam games and tied it all up, zip size continues to be the same no matter the changes 3.68GB, exported it Windows and it returns with the same result, non-steam games did not apply.

What I've noticed is that collections made on Linux are visible on all local machines, while creating a collection on Windows, the collection is only visible to Windows. So after multiple EmuDeck/SRM installs I have multiple broken collections across multiple machines. It has been painstakingly fixed now but the naming is also an issue as you say, Steam Rom Manager isn't consistent in parsing between these two systems due to broken matches and inconsistency with collections.

**Comment by Tormak9970** [comment]
Damn that sucks, no rush

**Comment by Tormak9970** [comment]
@brianx87 Closing this for now. If you find time to send me your shortcuts.vdf I'll re-open it. I still haven't been able to reproduce this
